# Which alignment tool should we use? Options are:
# - bwa: for very short (i.e. 36bp) reads
# - bowtie: for everything else
aligner: bowtie
# Should input FASTQ files be trimmed for quality?
trim: True
# Is the data paired-end?
paired_end: True
# Which output formats should be returned?
bedgraph: True
bigwig: False
# When generating the bedgraph and/or bigwig files, how wide (bp) should each
# bin be?
binsize: 10000
# Each ChIP-seq file needs a corresponding input file, to control
# for non-random patterns in which regions of the genome are sequenced.
# Below, the keys are the ChIP sample names, and the values are the input
# files.
inputs:
    GSK3A2-CTCF: GSK3A2-Input
    GSK3A2-RAD21: GSK3A2-Input
    Scr1-CTCF: Scr1-Input
    Scr1-RAD21: Scr1-Input
